[package]
name = "population_health"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "population_health"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
population_health_integrity = { path = "../integrity" }
