[package]
name = "fhir_bridge_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

mycelix_health_shared = { path = "../../shared" }
