[package]
name = "fhir_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

fhir_bridge_integrity = { path = "../integrity" }
mycelix-health-shared = { path = "../../shared" }
