[package]
name = "verifiable_credentials"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "verifiable_credentials"

[dependencies]
hdk = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
verifiable_credentials_integrity = { path = "../integrity" }
