[package]
name = "credentials_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "credentials_integrity"

[dependencies]
holochain_serialized_bytes = { workspace = true }
hdi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
