[package]
name = "population_health_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "population_health_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
