[package]
name = "disaster_response"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "disaster_response"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
disaster_response_integrity = { path = "../integrity" }
